### ISSUE TITLE
 http: connection has been hijacked

### ISSUE THREAD

**Issue by ahkimkoo** [vearne/gin-timeout#14]
2021/11/29 15:34:11 [Recovery] 2021/11/29 - 15:34:11 panic recovered:
http: connection has been hijacked
/home/cherokee/project/goproject/pkg/mod/github.com/vearne/gin-timeout@v0.0.8/timeout.go:81 (0x154ab84)
	Timeout.func1: panic(err)
/home/cherokee/project/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165 (0xbf809c)
	(*Context).Next: c.handlers[c.index](c)
/home/project/hangyanshe/go/src/hys-api/api/middleware/middlerware.go:24 (0x11a527a)
	Cors.func1: c.Next()
/home/cherokee/project/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165 (0xbf809c)
	(*Context).Next: c.handlers[c.index](c)
/home/cherokee/project/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.3/logger.go:241 (0xc08371)
	LoggerWithConfig.func1: c.Next()
/home/cherokee/project/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165 (0xbf809c)
	(*Context).Next: c.handlers[c.index](c)
/home/cherokee/project/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.3/recovery.go:99 (0xc09984)
	CustomRecoveryWithWriter.func1: c.Next()
/home/cherokee/project/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.3/context.go:165 (0xbf809c)
	(*Context).Next: c.handlers[c.index](c)
/home/cherokee/project/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.3/gin.go:489 (0xc06493)
	(*Engine).handleHTTPRequest: c.Next()
/home/cherokee/project/goproject/pkg/mod/github.com/gin-gonic/gin@v1.7.3/gin.go:445 (0xc05f9a)
	(*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/home/app/go/src/net/http/server.go:2878 (0x879319)
	serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/home/app/go/src/net/http/server.go:1929 (0x872e57)
	(*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/home/app/go/src/runtime/asm_amd64.s:1581 (0x46a2e0)
	goexit: BYTE	$0x90	// NOP

**Comment by vearne** [comment]
How to reproduce your problem？

**Comment by daychou** [comment]
这个timeout我使用也有问题，只要业务逻辑存在panic，这是代码中有bug导致panic，但timeout会recover住，显示在timeout这里panic，从而无法发现具体业务是哪一段代码导致panic

**Comment by vearne** [comment]
这个问题目前我也没有找到好办法来解决。

**Comment by vearne** [comment]
> 这个timeout我使用也有问题，如果业务逻辑代码中有bug导致panic，但timeout会recover住，报错信息显示在timeout这里panic，从而无法发现具体业务是哪一段代码导致panic

见tag v0.1.0   [示例](https://github.com/vearne/gin-timeout/blob/master/example/panic.go)

**Comment by daychou** [comment]
> > 这个timeout我使用也有问题，如果业务逻辑代码中有bug导致panic，但timeout会recover住，报错信息显示在timeout这里panic，从而无法发现具体业务是哪一段代码导致panic
> 
> 见tag v0.1.0 [示例](https://github.com/vearne/gin-timeout/blob/master/example/panic.go)

谢谢，升了0.1.0后就正常了，达到了预期结果。
