### ISSUE TITLE
c.Writer.Size() 没有正确记录

### ISSUE THREAD

**Issue by coldbrewtea** [vearne/gin-timeout#19]
`TimeoutWriter`中重写了`Write(b []byte) (int, error)`，没有更新相关size变量逻辑；
Write之后调用`TimeoutWriter.Size()` -> `gin.ResponseWriter.Size()` 得到的结果还是nowritten=-1；

由于`gin.ResponseWriter`中的`size`是私有变量，也没有提供变更方法，是否考虑在`TimeoutWriter`中重写`Size() int`方法？

**Comment by vearne** [comment]
add  Size() for TimeoutWriter, please use v0.1.2

**Comment by vearne** [comment]
不会导致超时情况的DefaultMsg无法成功写入Response中?因为 tw.ResponseWriter.Write([]byte(tw.DefaultMsg)) 而不是TimeoutWriter.Write()。我又更新了一个版本v0.1.3，之前超时的情况下，TimeoutWriter.Size() 返回有问题。

**Comment by vearne** [comment]
具体 [normal.go](https://github.com/vearne/gin-timeout/blob/master/example/normal.go)
