### ISSUE TITLE
middleware cannot access gin.Context map 

### ISSUE THREAD

**Issue by AmitShah** [vearne/gin-timeout#35]
My controller calls `context.Set(key,value)` and my mw is added prior to the timeout mw because I need the response status.  But my mw reads nil for `context.Keys`.   I think this is due to the following code defined timeout.go:
 ```
		cp := *c //nolint: govet
		c.Abort()
		c.Keys = nil 
 ```
 
is it plausible to solve with: 
```
                case <-finish:
			...
			c.Keys = cp.Keys
```

**Comment by vearne** [comment]
Can you provide a complete example?
