### ISSUE TITLE
客户端主动取消的，也会打日志报超时了

### ISSUE THREAD

**Issue by godsoul** [vearne/gin-timeout#7]
客户端主动取消的，也会打日志报超时了，有办法客户端原因主动关闭的，没到超时时间，不打日志吗？

**Comment by godsoul** [comment]
还有个问题，出现了panic，gin的recover都没捕获到
`goroutine 82613 [IO wait]:
internal/poll.runtime_pollWait(0x7f70728eb7a8, 0x72, 0xf47f00)
	/Users/godsoul/soft/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000ba898, 0x72, 0xf47f00, 0x13fe530, 0x0)
	/Users/godsoul/soft/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/Users/godsoul/soft/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000ba880, 0xc000572000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/godsoul/soft/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0000ba880, 0xc000572000, 0x1000, 0x1000, 0xc00008fb50, 0xd27180, 0x7f70728eb888)
	/Users/godsoul/soft/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0016d9b08, 0xc000572000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/godsoul/soft/go/src/net/net.go:182 +0x8e
net/http.(*connReader).Read(0xc0018cc3f0, 0xc000572000, 0x1000, 0x1000, 0xc026d87e8858fb86, 0x14ad426045e, 0x1525240)
	/Users/godsoul/soft/go/src/net/http/server.go:798 +0x1ad
bufio.(*Reader).fill(0xc001859800)
	/Users/godsoul/soft/go/src/bufio/bufio.go:101 +0x105
bufio.(*Reader).Peek(0xc001859800, 0x4, 0x14ad426045e, 0x1525240, 0x0, 0x0, 0x1525240)
	/Users/godsoul/soft/go/src/bufio/bufio.go:139 +0x4f
net/http.(*conn).serve(0xc000594000, 0xf57700, 0xc0016de0c0)
	/Users/godsoul/soft/go/src/net/http/server.go:1950 +0xa14
created by net/http.(*Server).Serve
	/Users/godsoul/soft/go/src/net/http/server.go:2969 +0x36c`

**Comment by godsoul** [comment]
中间件设置 timeout.WithTimeout(5*time.Second),
http server设置 
ReadTimeout:    10 * time.Second,
WriteTimeout:   10 * time.Second,

是不是我设置 http 这2个超时时间比用你的中间件时间长导致的？context被关了。

**Comment by godsoul** [comment]
goroutine 2670148 [semacquire]:
sync.runtime_SemacquireMutex(0xc00046e844, 0x0, 0x1)
	/Users/godsoul/soft/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00046e840)
	/Users/godsoul/soft/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
	/Users/godsoul/soft/go/src/sync/mutex.go:81
database/sql.(*DB).putConn(0xc00046e820, 0xc010713cb0, 0x0, 0x0, 0xf4f401)
	/Users/godsoul/soft/go/src/database/sql/sql.go:1350 +0x385
database/sql.(*driverConn).releaseConn(...)
	/Users/godsoul/soft/go/src/database/sql/sql.go:475
database/sql.(*Rows).close(0xc037ffd700, 0x0, 0x0, 0x0, 0x0)
	/Users/godsoul/soft/go/src/database/sql/sql.go:3180 +0x164
database/sql.(*Rows).Close(...)
	/Users/godsoul/soft/go/src/database/sql/sql.go:3151
database/sql.(*Rows).Next(0xc037ffd700, 0xc037ffd700)
	/Users/godsoul/soft/go/src/database/sql/sql.go:2839 +0xb8
github.com/jinzhu/gorm.queryCallback(0xc02a1c9080)
	/Users/godsoul/code/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/callback_query.go:76 +0x413
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc02a1c9080, 0xc000474980, 0x3, 0x4, 0x0)
	/Users/godsoul/code/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/scope.go:869 +0x83
github.com/jinzhu/gorm.(*DB).First(0xc02a1d6750, 0xd28a40, 0xc02a1c9000, 0x0, 0x0, 0x0, 0xc02a1d6750)
	/Users/godsoul/code/go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/main.go:334 +0x125
sj_api/match/models.FindMemberById(0x0, 0x1b, 0x20, 0xc009671400, 0x0)
	/Users/godsoul/code/golang/sj_api/match/models/team_member_data.go:168 +0x165
sj_api/match/models.TeamMemberDataByAcc(0x0, 0xc001582a66, 0x20, 0x0, 0x20)
	/Users/godsoul/code/golang/sj_api/match/models/team_member_data.go:34 +0x105
sj_api/match/controllers.MemberInfo(0xc00fc9c400)
	/Users/godsoul/code/golang/sj_api/match/controllers/data_analyze.go:75 +0xe5
github.com/gin-gonic/gin.(*Context).Next(0xc00fc9c400)
	/Users/godsoul/code/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 +0x3b
github.com/vearne/gin-timeout.Timeout.func1.1(0xc009eef680, 0xc00fc9c400, 0xc0053df320)
	/Users/godsoul/code/go/pkg/mod/github.com/vearne/gin-timeout@v0.0.6/timeout.go:58 +0x57
created by github.com/vearne/gin-timeout.Timeout.func1
	/Users/godsoul/code/go/pkg/mod/github.com/vearne/gin-timeout@v0.0.6/timeout.go:52 +0x34a

有时候panic就整个程序挂了，有时候不会。

**Comment by godsoul** [comment]
go func() {
			defer func() {
				if p := recover(); p != nil {
					panicChan <- p
				}
			}()
			c.Next()
			finish <- struct{}{}
		}()
c.Next() 这里挂了

**Comment by godsoul** [comment]
应该是 panicChan 有问题，线上量大的时候，不知道是被关了，还是太多panic阻塞了

**Comment by vearne** [comment]
panic需要自己捕获，gin-timeout不捕获。
见示例[panic.go](https://github.com/vearne/gin-timeout/blob/master/example/panic.go)
你也可以使用gin官方提供的Recovery中间件来捕获异常

**Comment by vearne** [comment]
golang里面每个协程都需要单独recover异常。gin-timeout会recover异常并向上抛出
见示例
[panic.go](https://github.com/vearne/gin-timeout/blob/master/example/panic.go)

**Comment by godsoul** [comment]
用了MyRecovery这个，还是会挂，现在我不网上抛，好像正常了

**Comment by vearne** [comment]
> 客户端主动取消的，也会打日志报超时了，有办法客户端原因主动关闭的，没到超时时间，不打日志吗？

这个无解，客户端主动取消，服务端没法感知，还是会继续执行的。

**Comment by xtony77** [comment]
If the client cancel the request, but wants to handle the callback, maybe can try this.
But my test result is gin console will still print a 408 warning request log.

```
timeoutLimit := 60 * time.Second
r.Use(func(c *gin.Context) {
    timeoutStart := time.Now()
    c.Next()
    if time.Now().Sub(timeoutStart).Seconds() > timeoutLimit.Seconds() && c.Writer.Status() == http.StatusRequestTimeout {
        // handle callback function
    }
})
r.Use(timeout.Timeout(
    timeout.WithTimeout(timeoutLimit),
    timeout.WithErrorHttpCode(http.StatusRequestTimeout),
    timeout.WithDefaultMsg(`{"code":408,"message":"Request Timeout"}`),
))
```

**Comment by coldbrewtea** [comment]
超时的情况应该是可以通过判断ctx.Err()区分出来的？
因为实际超时控制是通过`context.WithTimeout`完成，根据`WithDeadline`源码和context的注释来看，超时的情况Err应该是`DeadlineExceeded`
